#index:
#    path: /
#    controller: App\Controller\DefaultController::index


register:
    path: /register
    controller: App\Controller\RegisterController::register

login:
    path: /login
    controller: App\Controller\SecurityController::login    

Admin:
    path: /admin
    controller: App\Controller\Admin\AdminController::users

Admin.remove:
    path: /admin/{id}/remove
    controller: App\Controller\Admin\AdminController::removeUser

Admin.update:
    path: /admin/{id}/update
    controller: App\Controller\Admin\AdminController::updateUser