#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
  path: /register
  controller: App\Controller\RegisterController::register

admin:
  path: /admin
  controller: App\Controller\Admin\AdminController::users


admin.remove:
  path: /admin/{id}/remove
  controller: App\Controller\Admin\AdminController::removeUser

login:
  path: /login
  controller: App\Controller\SecurityController::login

admin.edit:
  path: /admin/edit/{id}
  controller: App\Controller\Admin\AdminController::editUser

edit.password:
  path: /edit/{id}
  controller: App\Controller\UserPasswordController::editPassword